services:
    bot:
        container_name: bot
        build: .
        volumes:
            - ./qr:/app/qr
            - ./session_data:/app/session_data
            - ./src:/app/src
        env_file:
            - .env
        command: npm run start:reload
